#!/bin/bash
# Push KRISPER VS Code extension to GitHub

echo "🚀 Pushing KRISPER VS Code Extension to GitHub"
echo "=============================================="
echo ""
echo "Since we need GitHub authentication, you have a few options:"
echo ""
echo "Option 1: Use GitHub CLI (recommended)"
echo "---------------------------------------"
echo "1. Install gh: sudo apt install gh"
echo "2. Authenticate: gh auth login"
echo "3. Run: gh repo create echo313unfolding/krisper-vscode --public --source=. --push"
echo ""
echo "Option 2: Use Personal Access Token"
echo "-----------------------------------"
echo "1. Go to: https://github.com/settings/tokens"
echo "2. Create a token with 'repo' permissions"
echo "3. Run: git push https://YOUR_TOKEN@github.com/echo313unfolding/krisper-vscode.git master"
echo ""
echo "Option 3: Use SSH (if configured)"
echo "---------------------------------"
echo "1. Change remote: git remote set-url origin git@github.com:echo313unfolding/krisper-vscode.git"
echo "2. Push: git push -u origin master"
echo ""
echo "After pushing, we'll publish to VS Code Marketplace!"