#!/bin/bash

echo "🚀 Quick Push to echo313unfolding GitHub"
echo "========================================"
echo ""
echo "This will push KRISPER + Bio_Poetica VS Code extension"
echo "Using the same credentials as your main KRISPER repo"
echo ""
echo "Options:"
echo ""
echo "1. If you have GitHub CLI authenticated:"
echo "   gh repo create echo313unfolding/krisper-vscode --public --source=. --push"
echo ""
echo "2. If you used a Personal Access Token for KRISPER:"
echo "   Use the same token here!"
echo ""
echo "3. Manual steps:"
echo "   a. Go to: https://github.com/new"
echo "   b. Name: krisper-vscode"
echo "   c. Owner: echo313unfolding" 
echo "   d. Public repository"
echo "   e. Create repository"
echo "   f. Then run: git push -u origin master"
echo ""
echo "The extension includes:"
echo "✅ KRISPER - Plain English to code"
echo "✅ Bio_Poetica - Cross-language biological programming"
echo "✅ GitHub Copilot compatibility"
echo "✅ 15+ language support"